[archives]
password_list = virus
                sophos
                infected
                test
                123
                777
                2020
                2021

[office]
password_list = VelvetSweatshop
                infected
                virus
                1234
                321
                0611
                june19
                123
                123456
                777
                222
                111
                333
                444
                555
                666
                888
                999
                258
                147
                799
                2020
                2021
